---
abstract: unknown
author:
  - unknown
build_requires:
  IO::CaptureOutput: 1.0801
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-CheckLib
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  File::Spec: 0
  File::Temp: 0.16
  perl: 5.00405
resources:
  repository: http://github.com/mattn/p5-Devel-CheckLib
version: 0.99
