# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-CheckLib
version:      0.5
version_from: lib/Devel/CheckLib.pm
installdirs:  site
requires:
    File::Temp:                    0.16
    IO::CaptureOutput:             1.0801
    Test::More:                    0.62

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
