--- #YAML:1.0
name:                Devel-CheckLib
version:             0.7
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Temp:                    0.16
    IO::CaptureOutput:             1.0801
    Test::More:                    0.62
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
