--- #YAML:1.0
name:               Devel-CheckLib
version:            0.8
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Exporter:           0
    File::Spec:         0
    File::Temp:         0.16
    IO::CaptureOutput:  1.0801
    perl:               5.00405
    Test::More:         0.62
resources:
    repository:  http://github.com/mattn/p5-Devel-CheckLib
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
